spring:
  profiles:
    active: prod

clock:
  run:
    duration: 3
    token: Bearer valid-token

logging:
  level:
    root: INFO
    org.apache.tomcat: WARN
    org.apache.coyote.http11.Http11Processor: ERROR